[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
    "npm ci",
    "cd src/ui && npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "cd src/ui && npm run build"
]

[start]
cmd = "npm start"
